export enum CandidateStatus {
  ACTIVE = 'ACTIVE',
  ELIMINATED = 'ELIMINATED',
  WINNER = 'WINNER',
}

export enum AddedReason {
  AI_RECOMMENDED = 'AI_RECOMMENDED',
  USER_SEARCHED = 'USER_SEARCHED',
  FROM_TEMPLATE = 'FROM_TEMPLATE',
  FROM_COMMUNITY = 'FROM_COMMUNITY',
}
