import {
  Journey,
  JourneySnapshot,
  NotificationItem,
  Candidate,
  CommunityJourney,
  CarInfo,
  TimelineEvent,
} from '@/types/api';
import { ChatMessage } from '@/store/chat.store';

// --- Active Journey ---
export const mockJourney: Journey = {
  id: 'mock-journey-1',
  userId: 'mock-user-1',
  title: '25万家用SUV选购',
  stage: 'COMPARISON',
  status: 'ACTIVE',
  requirements: {
    budget: { min: 200000, max: 280000 },
    fuelType: '增程',
    bodyType: 'SUV',
    seats: 5,
    useCases: ['家用', '通勤'],
    priorities: ['空间大', '续航无焦虑', '智能座舱'],
  },
  aiConfidenceScore: 0.72,
};

// --- Cars ---
export const mockCars: CarInfo[] = [
  {
    id: 'car-1',
    brand: '理想',
    model: 'L6',
    variant: 'Max',
    type: 'SUV',
    fuelType: 'EREV',
    msrp: 249800,
    baseSpecs: { range: 1390, acceleration: 5.4, length: 4925 },
  },
  {
    id: 'car-2',
    brand: '问界',
    model: 'M7',
    variant: 'Plus',
    type: 'SUV',
    fuelType: 'EREV',
    msrp: 249800,
    baseSpecs: { range: 1300, acceleration: 6.2, length: 4975 },
  },
  {
    id: 'car-3',
    brand: '小鹏',
    model: 'G6',
    variant: '702 Max',
    type: 'SUV',
    fuelType: 'BEV',
    msrp: 209900,
    baseSpecs: { range: 702, acceleration: 3.9, length: 4753 },
  },
];

// --- Candidates ---
export const mockCandidates: Candidate[] = [
  {
    id: 'cand-1',
    journeyId: 'mock-journey-1',
    carId: 'car-1',
    status: 'ACTIVE',
    aiMatchScore: 0.92,
    userInterestScore: 0.85,
    priceAtAdd: 249800,
    userNotes: '空间大，增程无续航焦虑',
    eliminationReason: null,
    matchTags: ['符合预算', '家用首选', '长续航'],
    recommendReason: '增程方案兼顾长途和日常，和你说的周末自驾需求很配',
    relevantDimensions: ['续航', '空间', '价格'],
    candidateRankScore: 0.91,
    car: mockCars[0],
  },
  {
    id: 'cand-2',
    journeyId: 'mock-journey-1',
    carId: 'car-2',
    status: 'ACTIVE',
    aiMatchScore: 0.85,
    userInterestScore: 0.70,
    priceAtAdd: 249800,
    userNotes: '华为智驾体验好',
    eliminationReason: null,
    matchTags: ['智驾突出', '空间够用'],
    recommendReason: '如果你更看重智能驾驶体验，这台车会更符合你的关注点',
    relevantDimensions: ['智驾', '空间', '价格'],
    candidateRankScore: 0.84,
    car: mockCars[1],
  },
  {
    id: 'cand-3',
    journeyId: 'mock-journey-1',
    carId: 'car-3',
    status: 'ACTIVE',
    aiMatchScore: 0.78,
    userInterestScore: 0.60,
    priceAtAdd: 209900,
    userNotes: null,
    eliminationReason: null,
    matchTags: ['价格更低', '纯电补能方便'],
    recommendReason: '预算更紧时，这台车能把购车成本压得更低',
    relevantDimensions: ['价格', '续航', '能耗'],
    candidateRankScore: 0.76,
    car: mockCars[2],
  },
];

export const mockTimelineEvents: TimelineEvent[] = [
  {
    id: 'te-1',
    journeyId: 'mock-journey-1',
    type: 'STAGE_CHANGED',
    content: '旅程开始，进入认知期',
    metadata: { stage: 'AWARENESS' },
    createdAt: '2026-03-20T10:00:00Z',
  },
  {
    id: 'te-2',
    journeyId: 'mock-journey-1',
    type: 'REQUIREMENT_UPDATED',
    content: '需求已更新：预算25-35万，家用SUV',
    metadata: { budgetMin: 25, budgetMax: 35, useCases: ['家用'] },
    createdAt: '2026-03-20T10:30:00Z',
  },
  {
    id: 'te-3',
    journeyId: 'mock-journey-1',
    type: 'CANDIDATE_ADDED',
    content: 'AI 推荐了理想 L6',
    metadata: { candidateId: 'cand-1', carName: '理想 L6', matchTags: ['符合预算', '家用首选'] },
    createdAt: '2026-03-21T09:00:00Z',
  },
  {
    id: 'te-4',
    journeyId: 'mock-journey-1',
    type: 'CANDIDATE_ADDED',
    content: 'AI 推荐了问界 M7',
    metadata: { candidateId: 'cand-2', carName: '问界 M7', matchTags: ['智驾突出'] },
    createdAt: '2026-03-21T14:00:00Z',
  },
  {
    id: 'te-5',
    journeyId: 'mock-journey-1',
    type: 'STAGE_CHANGED',
    content: '旅程进入对比期',
    metadata: { stage: 'COMPARISON' },
    createdAt: '2026-03-22T10:00:00Z',
  },
  {
    id: 'te-6',
    journeyId: 'mock-journey-1',
    type: 'AI_INSIGHT',
    content: '你在续航话题上花了最多时间，看来这是你最关注的维度',
    metadata: { dimension: '续航', confidence: 0.85 },
    createdAt: '2026-03-23T15:00:00Z',
  },
];

// --- Snapshot ---
export const mockSnapshot: JourneySnapshot = {
  id: 'snap-1',
  journeyId: 'mock-journey-1',
  narrativeSummary:
    '您正在深度对比三款25万级SUV。理想L6在空间和续航方面最符合您的需求，问界M7的智驾体验值得关注，小鹏G6性价比突出但纯电续航可能影响长途出行。建议下一步实地试驾理想L6和问界M7，重点感受空间和智驾表现。',
  keyInsights: [
    {
      insight: '理想L6综合匹配度最高',
      evidence: '增程续航1390km消除里程焦虑，五座空间同级最优',
      confidence: 0.92,
    },
    {
      insight: '问界M7智驾体验领先',
      evidence: '华为ADS 2.0高速NOA表现优于竞品',
      confidence: 0.85,
    },
    {
      insight: '小鹏G6性价比突出但有短板',
      evidence: '价格最低、加速最快，但纯电702km冬季打折明显',
      confidence: 0.78,
    },
  ],
  nextSuggestedActions: ['预约理想L6试驾', '对比三车保值率', '查看车主真实油耗反馈'],
  generatedAt: new Date().toISOString(),
};

// --- Notifications ---
export const mockNotifications: NotificationItem[] = [
  {
    id: 'notif-1',
    type: 'AI_INSIGHT',
    title: 'AI 发现新洞察',
    body: '理想L6近期终端优惠增大，部分地区优惠达1.5万元',
    metadata: {},
    relatedCarId: 'car-1',
    isRead: false,
    createdAt: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'notif-2',
    type: 'PRICE_CHANGE',
    title: '价格变动提醒',
    body: '问界M7 Plus指导价下调5000元',
    metadata: {},
    relatedCarId: 'car-2',
    isRead: false,
    createdAt: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: 'notif-3',
    type: 'STAGE_CHANGE',
    title: '旅程阶段推进',
    body: '根据您的对比行为，AI建议进入「深度对比」阶段',
    metadata: {},
    relatedCarId: null,
    isRead: true,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
];

// --- Chat History ---
export const mockChatMessages: ChatMessage[] = [
  {
    id: 'msg-1',
    kind: 'text',
    role: 'USER',
    content: '我想买一台25万左右的家用SUV，增程优先，主要家用和通勤',
    timestamp: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'msg-2',
    kind: 'text',
    role: 'ASSISTANT',
    content:
      '好的！根据您的需求——预算25万、增程优先、家用通勤，我来帮您筛选。关键需求确认：\n\n1. 座位数：5座够用还是需要6/7座？\n2. 对智能驾驶有要求吗？\n3. 品牌有偏好吗？',
    timestamp: new Date(Date.now() - 3500000).toISOString(),
  },
  {
    id: 'msg-3',
    kind: 'text',
    role: 'USER',
    content: '5座就行，智驾最好有，品牌不限',
    timestamp: new Date(Date.now() - 3400000).toISOString(),
  },
  {
    id: 'msg-4',
    kind: 'text',
    role: 'ASSISTANT',
    content: '明白了，我为您搜索了符合条件的车型。以下三款是25万级增程/纯电SUV中最匹配的：',
    timestamp: new Date(Date.now() - 3300000).toISOString(),
  },
  {
    id: 'msg-5',
    kind: 'car_results',
    journeyId: 'mock-journey-1',
    cars: [
      {
        id: 'car-1',
        brand: '理想',
        model: 'L6',
        type: 'SUV',
        fuelType: 'EREV',
        msrp: 249800,
        subtitle: '增程 · 五座 · 24.98万起',
        matchScore: 92,
        addedCandidate: mockCandidates[0],
      },
      {
        id: 'car-2',
        brand: '问界',
        model: 'M7',
        type: 'SUV',
        fuelType: 'EREV',
        msrp: 249800,
        subtitle: '增程 · 五座 · 24.98万起',
        matchScore: 85,
        addedCandidate: mockCandidates[1],
      },
      {
        id: 'car-3',
        brand: '小鹏',
        model: 'G6',
        type: 'SUV',
        fuelType: 'BEV',
        msrp: 209900,
        subtitle: '纯电 · 五座 · 20.99万起',
        matchScore: 78,
        addedCandidate: mockCandidates[2],
      },
    ],
    timestamp: new Date(Date.now() - 3200000).toISOString(),
  },
  {
    id: 'msg-6',
    kind: 'text',
    role: 'USER',
    content: '帮我对比一下这三款的续航和空间',
    timestamp: new Date(Date.now() - 1800000).toISOString(),
  },
  {
    id: 'msg-7',
    kind: 'text',
    role: 'ASSISTANT',
    content:
      '三车续航与空间对比：\n\n**续航（CLTC）**\n• 理想L6：1390km（增程）— 无续航焦虑\n• 问界M7：1300km（增程）— 同样省心\n• 小鹏G6：702km（纯电）— 日常够用，冬季/长途需规划\n\n**车身尺寸（长×宽×高mm）**\n• 理想L6：4925×1960×1735 — 同级最宽\n• 问界M7：4975×1930×1763 — 最长最高\n• 小鹏G6：4753×1920×1650 — 最紧凑\n\n**后排空间体感**\n理想L6 ≈ 问界M7 > 小鹏G6\n\n如果长途出行较多，增程方案（理想/问界）更省心。如果主要市内通勤且有家充，小鹏G6的纯电方案用车成本最低。\n\n需要我进一步对比智驾或保值率吗？',
    timestamp: new Date(Date.now() - 1700000).toISOString(),
  },
];

// --- Community ---
export const mockCommunityJourneys: CommunityJourney[] = [
  {
    id: 'mock-1',
    journeyId: 'j1',
    title: '家用 SUV 选购之路：从迷茫到提车理想 L6',
    description: '预算25万，从完全不懂车到最终选定理想L6的完整过程。对比了问界M7、小鹏G6，最终因增程无续航焦虑而选择理想。',
    publishSummary: '25万家用SUV三选一，最终因为增程更省心选了理想 L6。',
    publishedFormats: ['story', 'template'],
    tags: { budgetMin: 20, budgetMax: 28, useCases: ['家用', '通勤'], candidateNames: ['理想 L6', '问界 M7', '小鹏 G6'] },
    storyContent: {
      stages: [
        {
          stage: 'AWARENESS',
          headline: '先把需求说清楚',
          narrative: '预算卡在 25 万左右，主要是家用和通勤，所以一开始就把空间、续航焦虑和后期成本当成最重要的判断标准。',
          candidates: ['理想 L6', '问界 M7', '小鹏 G6'],
          keyDimension: '空间',
        },
        {
          stage: 'COMPARISON',
          headline: '三款车进入深度对比',
          narrative: '对比下来，小鹏 G6 的纯电成本最低，但理想 L6 和问界 M7 在长途补能上更省心，家庭使用场景下明显更稳。',
          candidates: ['理想 L6', '问界 M7', '小鹏 G6'],
          keyDimension: '续航',
        },
        {
          stage: 'DECISION',
          headline: '最终选定理想 L6',
          narrative: '真正让我下决心的是增程方案带来的确定性。试驾后确认空间够用，长途没有补能焦虑，整体更像一台适合全家长期用的车。',
          candidates: ['理想 L6'],
          keyDimension: '综合体验',
        },
      ],
    },
    templateData: {
      dimensions: ['空间', '续航', '价格'],
      weights: { 空间: 0.35, 续航: 0.4, 价格: 0.25 },
      keyQuestions: ['家用场景下后排是否真的够用？', '长途补能是否会带来焦虑？', '预算内有没有更平衡的选择？'],
      candidateNames: ['理想 L6', '问界 M7', '小鹏 G6'],
    },
    visibility: 'PUBLIC',
    viewCount: 1842,
    likeCount: 256,
    commentCount: 43,
    forkCount: 89,
    contentStatus: 'APPROVED',
    publishedAt: '2026-03-20T10:00:00Z',
    user: { id: 'u1', nickname: '老张选车记' },
    journey: { id: 'j1', status: 'COMPLETED', stage: 'PURCHASE' },
  },
  {
    id: 'mock-2',
    journeyId: 'j2',
    title: '新手妈妈的第一台车：安全是唯一标准',
    description: '宝宝刚出生，需要一台安全性拉满的车。从沃尔沃XC60到极氪007，AI帮我从C-NCAP和E-NCAP数据中找到了答案。',
    publishSummary: '孩子出生后重新看车，最后把安全冗余放在第一位。',
    publishedFormats: ['story'],
    tags: { budgetMin: 25, budgetMax: 35, useCases: ['家用', '安全'], candidateNames: ['沃尔沃 XC60', '极氪 007'] },
    visibility: 'PUBLIC',
    viewCount: 923,
    likeCount: 178,
    commentCount: 31,
    forkCount: 24,
    contentStatus: 'APPROVED',
    publishedAt: '2026-03-19T14:30:00Z',
    user: { id: 'u2', nickname: '小鱼妈妈' },
    journey: { id: 'j2', status: 'COMPLETED', stage: 'PURCHASE' },
  },
  {
    id: 'mock-3',
    journeyId: 'j3',
    title: '30万预算越野车深度对比：坦克300 vs 方程豹豹5',
    description: '周末喜欢去户外，需要有一定越野能力但日常通勤也舒适的车型。',
    publishSummary: '想兼顾户外和通勤，最后先把越野能力和日常舒适拆开看。',
    publishedFormats: ['report', 'template'],
    tags: { budgetMin: 25, budgetMax: 35, useCases: ['越野', '通勤'], candidateNames: ['坦克 300', '豹 5'] },
    reportData: {
      userProfile: {
        budget: '25-35万',
        fuelPreference: '不限',
        useCases: ['越野', '通勤'],
        coreDimensions: ['通过性', '舒适性', '价格'],
      },
      comparison: [
        { carName: '坦克 300', scores: { 通过性: 92, 舒适性: 68, 价格: 78 }, highlight: '越野基础扎实，改装生态成熟。' },
        { carName: '豹 5', scores: { 通过性: 88, 舒适性: 81, 价格: 72 }, highlight: '日常驾驶质感更现代，城市通勤更友好。' },
      ],
      recommendation: {
        carName: '豹 5',
        reasoning: '如果通勤占比更高，它在舒适性和整体平衡感上更适合作为日常主力。',
      },
    },
    templateData: {
      dimensions: ['通过性', '舒适性', '价格'],
      weights: { 通过性: 0.45, 舒适性: 0.3, 价格: 0.25 },
      keyQuestions: ['真正的使用场景里越野占比有多高？', '通勤时是否能接受硬派底盘？'],
      candidateNames: ['坦克 300', '豹 5'],
    },
    visibility: 'PUBLIC',
    viewCount: 2105,
    likeCount: 312,
    commentCount: 67,
    forkCount: 156,
    contentStatus: 'APPROVED',
    publishedAt: '2026-03-18T09:15:00Z',
    user: { id: 'u3', nickname: '野路子' },
    journey: { id: 'j3', status: 'ACTIVE', stage: 'COMPARISON' },
  },
  {
    id: 'mock-4',
    journeyId: 'j4',
    title: '纯电通勤之选：比亚迪海豹 vs 特斯拉 Model 3',
    description: '每天通勤60km，家里有充电桩，纯电是最优解。但选国产还是特斯拉？AI从使用成本、保值率、智驾体验三个维度帮我分析。',
    publishSummary: '家充条件明确后，纯电成本优势开始变得非常直接。',
    publishedFormats: ['story'],
    tags: { budgetMin: 18, budgetMax: 25, useCases: ['通勤'], candidateNames: ['比亚迪 海豹', '特斯拉 Model 3'] },
    visibility: 'PUBLIC',
    viewCount: 1567,
    likeCount: 203,
    commentCount: 52,
    forkCount: 45,
    contentStatus: 'APPROVED',
    publishedAt: '2026-03-17T16:45:00Z',
    user: { id: 'u4', nickname: '电动老司机' },
    journey: { id: 'j4', status: 'COMPLETED', stage: 'PURCHASE' },
  },
  {
    id: 'mock-5',
    journeyId: 'j5',
    title: '人生第一台车：10万预算怎么选？',
    description: '刚毕业的打工人，预算有限但不想将就。从秦PLUS到缤果，每一分钱都要花在刀刃上。',
    publishSummary: '预算越紧，越要把真正高频用到的体验排在前面。',
    publishedFormats: ['story', 'template'],
    tags: { budgetMin: 8, budgetMax: 12, useCases: ['通勤', '日常'], candidateNames: ['秦 PLUS', '缤果'] },
    visibility: 'PUBLIC',
    viewCount: 3201,
    likeCount: 489,
    commentCount: 112,
    forkCount: 267,
    contentStatus: 'APPROVED',
    publishedAt: '2026-03-16T11:20:00Z',
    user: { id: 'u5', nickname: '省钱达人' },
    journey: { id: 'j5', status: 'COMPLETED', stage: 'PURCHASE' },
  },
  {
    id: 'mock-6',
    journeyId: 'j6',
    title: '商务座驾升级：从帕萨特到蔚来 ET7',
    description: '做业务需要有面子的车，从传统BBA到新势力，AI帮我算了一笔账：ET7的BaaS方案让月供降了40%。',
    publishSummary: '从传统商务轿车切到新势力，关键在于成本模型被重新算清楚了。',
    publishedFormats: ['report'],
    tags: { budgetMin: 35, budgetMax: 50, useCases: ['商务'], candidateNames: ['帕萨特', '蔚来 ET7'] },
    reportData: {
      userProfile: {
        budget: '35-50万',
        fuelPreference: '纯电优先',
        useCases: ['商务'],
        coreDimensions: ['形象', '成本', '舒适性'],
      },
      comparison: [
        { carName: '帕萨特', scores: { 形象: 70, 成本: 82, 舒适性: 76 }, highlight: '稳妥但惊喜不足。' },
        { carName: '蔚来 ET7', scores: { 形象: 88, 成本: 74, 舒适性: 90 }, highlight: 'BaaS 方案重新平衡了预算与体验。' },
      ],
      recommendation: {
        carName: '蔚来 ET7',
        reasoning: '如果商务场景更看重品牌感和乘坐体验，它提供了更明显的升级感。',
      },
    },
    visibility: 'PUBLIC',
    viewCount: 876,
    likeCount: 134,
    commentCount: 28,
    forkCount: 12,
    contentStatus: 'APPROVED',
    publishedAt: '2026-03-15T08:00:00Z',
    user: { id: 'u6', nickname: '业务老王' },
    journey: { id: 'j6', status: 'ACTIVE', stage: 'DECISION' },
  },
];
