import { Journey, JourneySnapshot, NotificationItem, Candidate, CommunityJourney, CarInfo } from '@/types/api';
import { ChatMessage } from '@/store/chat.store';

// --- Active Journey ---
export const mockJourney: Journey = {
  id: 'mock-journey-1',
  userId: 'mock-user-1',
  title: '25万家用SUV选购',
  stage: 'COMPARISON',
  status: 'ACTIVE',
  requirements: {
    budget: { min: 200000, max: 280000 },
    fuelType: '增程',
    bodyType: 'SUV',
    seats: 5,
    useCases: ['家用', '通勤'],
    priorities: ['空间大', '续航无焦虑', '智能座舱'],
  },
  aiConfidenceScore: 0.72,
};

// --- Cars ---
export const mockCars: CarInfo[] = [
  {
    id: 'car-1',
    brand: '理想',
    model: 'L6',
    variant: 'Max',
    type: 'SUV',
    fuelType: 'EREV',
    msrp: 249800,
    baseSpecs: { range: 1390, acceleration: 5.4, length: 4925 },
  },
  {
    id: 'car-2',
    brand: '问界',
    model: 'M7',
    variant: 'Plus',
    type: 'SUV',
    fuelType: 'EREV',
    msrp: 249800,
    baseSpecs: { range: 1300, acceleration: 6.2, length: 4975 },
  },
  {
    id: 'car-3',
    brand: '小鹏',
    model: 'G6',
    variant: '702 Max',
    type: 'SUV',
    fuelType: 'BEV',
    msrp: 209900,
    baseSpecs: { range: 702, acceleration: 3.9, length: 4753 },
  },
];

// --- Candidates ---
export const mockCandidates: Candidate[] = [
  {
    id: 'cand-1',
    journeyId: 'mock-journey-1',
    carId: 'car-1',
    status: 'ACTIVE',
    aiMatchScore: 0.92,
    userInterestScore: 0.85,
    priceAtAdd: 249800,
    userNotes: '空间大，增程无续航焦虑',
    eliminationReason: null,
    car: mockCars[0],
  },
  {
    id: 'cand-2',
    journeyId: 'mock-journey-1',
    carId: 'car-2',
    status: 'ACTIVE',
    aiMatchScore: 0.85,
    userInterestScore: 0.70,
    priceAtAdd: 249800,
    userNotes: '华为智驾体验好',
    eliminationReason: null,
    car: mockCars[1],
  },
  {
    id: 'cand-3',
    journeyId: 'mock-journey-1',
    carId: 'car-3',
    status: 'ACTIVE',
    aiMatchScore: 0.78,
    userInterestScore: 0.60,
    priceAtAdd: 209900,
    userNotes: null,
    eliminationReason: null,
    car: mockCars[2],
  },
];

// --- Snapshot ---
export const mockSnapshot: JourneySnapshot = {
  id: 'snap-1',
  journeyId: 'mock-journey-1',
  narrativeSummary:
    '您正在深度对比三款25万级SUV。理想L6在空间和续航方面最符合您的需求，问界M7的智驾体验值得关注，小鹏G6性价比突出但纯电续航可能影响长途出行。建议下一步实地试驾理想L6和问界M7，重点感受空间和智驾表现。',
  keyInsights: [
    {
      insight: '理想L6综合匹配度最高',
      evidence: '增程续航1390km消除里程焦虑，五座空间同级最优',
      confidence: 0.92,
    },
    {
      insight: '问界M7智驾体验领先',
      evidence: '华为ADS 2.0高速NOA表现优于竞品',
      confidence: 0.85,
    },
    {
      insight: '小鹏G6性价比突出但有短板',
      evidence: '价格最低、加速最快，但纯电702km冬季打折明显',
      confidence: 0.78,
    },
  ],
  nextSuggestedActions: ['预约理想L6试驾', '对比三车保值率', '查看车主真实油耗反馈'],
  generatedAt: new Date().toISOString(),
};

// --- Notifications ---
export const mockNotifications: NotificationItem[] = [
  {
    id: 'notif-1',
    type: 'AI_INSIGHT',
    title: 'AI 发现新洞察',
    body: '理想L6近期终端优惠增大，部分地区优惠达1.5万元',
    metadata: {},
    relatedCarId: 'car-1',
    isRead: false,
    createdAt: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'notif-2',
    type: 'PRICE_CHANGE',
    title: '价格变动提醒',
    body: '问界M7 Plus指导价下调5000元',
    metadata: {},
    relatedCarId: 'car-2',
    isRead: false,
    createdAt: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: 'notif-3',
    type: 'STAGE_CHANGE',
    title: '旅程阶段推进',
    body: '根据您的对比行为，AI建议进入「深度对比」阶段',
    metadata: {},
    relatedCarId: null,
    isRead: true,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
];

// --- Chat History ---
export const mockChatMessages: ChatMessage[] = [
  {
    id: 'msg-1',
    kind: 'text',
    role: 'USER',
    content: '我想买一台25万左右的家用SUV，增程优先，主要家用和通勤',
    timestamp: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'msg-2',
    kind: 'text',
    role: 'ASSISTANT',
    content:
      '好的！根据您的需求——预算25万、增程优先、家用通勤，我来帮您筛选。关键需求确认：\n\n1. 座位数：5座够用还是需要6/7座？\n2. 对智能驾驶有要求吗？\n3. 品牌有偏好吗？',
    timestamp: new Date(Date.now() - 3500000).toISOString(),
  },
  {
    id: 'msg-3',
    kind: 'text',
    role: 'USER',
    content: '5座就行，智驾最好有，品牌不限',
    timestamp: new Date(Date.now() - 3400000).toISOString(),
  },
  {
    id: 'msg-4',
    kind: 'text',
    role: 'ASSISTANT',
    content: '明白了，我为您搜索了符合条件的车型。以下三款是25万级增程/纯电SUV中最匹配的：',
    timestamp: new Date(Date.now() - 3300000).toISOString(),
  },
  {
    id: 'msg-5',
    kind: 'car_results',
    journeyId: 'mock-journey-1',
    cars: [
      {
        id: 'car-1',
        brand: '理想',
        model: 'L6',
        type: 'SUV',
        fuelType: 'EREV',
        msrp: 249800,
        subtitle: '增程 · 五座 · 24.98万起',
        matchScore: 92,
        addedCandidate: mockCandidates[0],
      },
      {
        id: 'car-2',
        brand: '问界',
        model: 'M7',
        type: 'SUV',
        fuelType: 'EREV',
        msrp: 249800,
        subtitle: '增程 · 五座 · 24.98万起',
        matchScore: 85,
        addedCandidate: mockCandidates[1],
      },
      {
        id: 'car-3',
        brand: '小鹏',
        model: 'G6',
        type: 'SUV',
        fuelType: 'BEV',
        msrp: 209900,
        subtitle: '纯电 · 五座 · 20.99万起',
        matchScore: 78,
        addedCandidate: mockCandidates[2],
      },
    ],
    timestamp: new Date(Date.now() - 3200000).toISOString(),
  },
  {
    id: 'msg-6',
    kind: 'text',
    role: 'USER',
    content: '帮我对比一下这三款的续航和空间',
    timestamp: new Date(Date.now() - 1800000).toISOString(),
  },
  {
    id: 'msg-7',
    kind: 'text',
    role: 'ASSISTANT',
    content:
      '三车续航与空间对比：\n\n**续航（CLTC）**\n• 理想L6：1390km（增程）— 无续航焦虑\n• 问界M7：1300km（增程）— 同样省心\n• 小鹏G6：702km（纯电）— 日常够用，冬季/长途需规划\n\n**车身尺寸（长×宽×高mm）**\n• 理想L6：4925×1960×1735 — 同级最宽\n• 问界M7：4975×1930×1763 — 最长最高\n• 小鹏G6：4753×1920×1650 — 最紧凑\n\n**后排空间体感**\n理想L6 ≈ 问界M7 > 小鹏G6\n\n如果长途出行较多，增程方案（理想/问界）更省心。如果主要市内通勤且有家充，小鹏G6的纯电方案用车成本最低。\n\n需要我进一步对比智驾或保值率吗？',
    timestamp: new Date(Date.now() - 1700000).toISOString(),
  },
];

// --- Community ---
export const mockCommunityJourneys: CommunityJourney[] = [
  {
    id: 'mock-1',
    journeyId: 'j1',
    title: '家用 SUV 选购之路：从迷茫到提车理想 L6',
    description: '预算25万，从完全不懂车到最终选定理想L6的完整过程。对比了问界M7、小鹏G6，最终因增程无续航焦虑而选择理想。',
    publishedFormats: ['story', 'template'],
    tags: { budgetMin: 20, budgetMax: 28, useCases: ['家用', '通勤'] },
    visibility: 'PUBLIC',
    viewCount: 1842,
    likeCount: 256,
    commentCount: 43,
    forkCount: 89,
    contentStatus: 'APPROVED',
    publishedAt: '2026-03-20T10:00:00Z',
    user: { id: 'u1', nickname: '老张选车记' },
    journey: { id: 'j1', status: 'COMPLETED', stage: 'PURCHASE' },
  },
  {
    id: 'mock-2',
    journeyId: 'j2',
    title: '新手妈妈的第一台车：安全是唯一标准',
    description: '宝宝刚出生，需要一台安全性拉满的车。从沃尔沃XC60到极氪007，AI帮我从C-NCAP和E-NCAP数据中找到了答案。',
    publishedFormats: ['story'],
    tags: { budgetMin: 25, budgetMax: 35, useCases: ['家用', '安全'] },
    visibility: 'PUBLIC',
    viewCount: 923,
    likeCount: 178,
    commentCount: 31,
    forkCount: 24,
    contentStatus: 'APPROVED',
    publishedAt: '2026-03-19T14:30:00Z',
    user: { id: 'u2', nickname: '小鱼妈妈' },
    journey: { id: 'j2', status: 'COMPLETED', stage: 'PURCHASE' },
  },
  {
    id: 'mock-3',
    journeyId: 'j3',
    title: '30万预算越野车深度对比：坦克300 vs 方程豹豹5',
    description: '周末喜欢去户外，需要有一定越野能力但日常通勤也舒适的车型。',
    publishedFormats: ['report', 'template'],
    tags: { budgetMin: 25, budgetMax: 35, useCases: ['越野', '通勤'] },
    visibility: 'PUBLIC',
    viewCount: 2105,
    likeCount: 312,
    commentCount: 67,
    forkCount: 156,
    contentStatus: 'APPROVED',
    publishedAt: '2026-03-18T09:15:00Z',
    user: { id: 'u3', nickname: '野路子' },
    journey: { id: 'j3', status: 'ACTIVE', stage: 'COMPARISON' },
  },
  {
    id: 'mock-4',
    journeyId: 'j4',
    title: '纯电通勤之选：比亚迪海豹 vs 特斯拉 Model 3',
    description: '每天通勤60km，家里有充电桩，纯电是最优解。但选国产还是特斯拉？AI从使用成本、保值率、智驾体验三个维度帮我分析。',
    publishedFormats: ['story'],
    tags: { budgetMin: 18, budgetMax: 25, useCases: ['通勤'] },
    visibility: 'PUBLIC',
    viewCount: 1567,
    likeCount: 203,
    commentCount: 52,
    forkCount: 45,
    contentStatus: 'APPROVED',
    publishedAt: '2026-03-17T16:45:00Z',
    user: { id: 'u4', nickname: '电动老司机' },
    journey: { id: 'j4', status: 'COMPLETED', stage: 'PURCHASE' },
  },
  {
    id: 'mock-5',
    journeyId: 'j5',
    title: '人生第一台车：10万预算怎么选？',
    description: '刚毕业的打工人，预算有限但不想将就。从秦PLUS到缤果，每一分钱都要花在刀刃上。',
    publishedFormats: ['story', 'template'],
    tags: { budgetMin: 8, budgetMax: 12, useCases: ['通勤', '日常'] },
    visibility: 'PUBLIC',
    viewCount: 3201,
    likeCount: 489,
    commentCount: 112,
    forkCount: 267,
    contentStatus: 'APPROVED',
    publishedAt: '2026-03-16T11:20:00Z',
    user: { id: 'u5', nickname: '省钱达人' },
    journey: { id: 'j5', status: 'COMPLETED', stage: 'PURCHASE' },
  },
  {
    id: 'mock-6',
    journeyId: 'j6',
    title: '商务座驾升级：从帕萨特到蔚来 ET7',
    description: '做业务需要有面子的车，从传统BBA到新势力，AI帮我算了一笔账：ET7的BaaS方案让月供降了40%。',
    publishedFormats: ['report'],
    tags: { budgetMin: 35, budgetMax: 50, useCases: ['商务'] },
    visibility: 'PUBLIC',
    viewCount: 876,
    likeCount: 134,
    commentCount: 28,
    forkCount: 12,
    contentStatus: 'APPROVED',
    publishedAt: '2026-03-15T08:00:00Z',
    user: { id: 'u6', nickname: '业务老王' },
    journey: { id: 'j6', status: 'ACTIVE', stage: 'DECISION' },
  },
];
